name: firstapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.1
  cloud_firestore: ^3.4.4
  provider: ^6.0.3
  flutter_slidable: ^2.0.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.6
  firebase_auth: ^3.6.4
  url_launcher: ^6.1.5
  http: ^0.13.5
  firebase_dynamic_links: ^4.3.6
  page_indicator: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - images/questLogo.png
  - assets/manIcon.jpg
  - assets/womanIcon.jpg
  - assets/bubbleBird.png
  - assets/bubbleMap.png
  - assets/bubbleEarth.png
  - assets/Banner.png
  - assets/icon.png
  - assets/icon02.png
  - assets/icon03.png
  - assets/icon04.png
  - assets/profile.png

